### ISSUE TITLE
No text limit on any of the quiz fields

### ISSUE THREAD

**Issue by Clembs** [Shinyhero36/quizthing#1]
The website fails to render very long strings of text properly (text overlapping on other elements, overflowing from their parent, etc), maybe consider implementing a text size limit?

Overview page:
![image](https://github.com/Shinyhero36/quizthing/assets/67973777/5d539736-a80e-4d62-9157-8a2987fa7bf3)

Quiz page:
![image](https://github.com/Shinyhero36/quizthing/assets/67973777/cad96097-fe03-4265-927b-5b1a9799ff7d)
![image](https://github.com/Shinyhero36/quizthing/assets/67973777/970cc51f-a9f3-431e-bb77-d7bafc224c17)

Community page (note how all quizzes align to the center of the page, thus shifting everything else way below the viewport):
![image](https://github.com/Shinyhero36/quizthing/assets/67973777/3ca1caec-0e3b-4c7d-9cc3-a61934741b22)

**Comment by Shinyhero36** [comment]
Thank you for reporting this issue, I made a [PR](https://github.com/Shinyhero36/quizthing/pull/6) which should fix all the issues you reported
