### ISSUE TITLE
Spam-duplicating a question will break the positioning

### ISSUE THREAD

**Issue by Clembs** [Shinyhero36/quizthing#10]
Steps to reproduce:
1. Create a question
2. Duplicate it a lot of times by spam clicking
3. See the chaos
4. Question 42 exists twice: one before Question 1, another after Question 41. Question 43 doesn't exist, sadly

![image](https://github.com/Shinyhero36/quizthing/assets/67973777/0424bcaf-553f-4c22-b635-34892be81b10)
![image](https://github.com/Shinyhero36/quizthing/assets/67973777/ade070cc-8d08-451f-b05e-fc3dfb7d4490)

**Comment by Shinyhero36** [comment]
Thanks for reporting the issue
