### ISSUE TITLE
Email duplication error shows the username as its message

### ISSUE THREAD

**Issue by Clembs** [Shinyhero36/quizthing#2]
When you register for an account using an email that's already been used, you get your current username as an error under your own username.

![image](https://github.com/Shinyhero36/quizthing/assets/67973777/270fd0fb-2d9c-4f0b-9d58-23c902b65396)

**Comment by Shinyhero36** [comment]
Fixed with [a6f1634c13dbdb0f95c893e611f5157ce063a1e7](https://github.com/Shinyhero36/quizthing/commit/a6f1634c13dbdb0f95c893e611f5157ce063a1e7)
