### ISSUE TITLE
Duplicating a question makes the next question still labelled "Question 1"

### ISSUE THREAD

**Issue by Clembs** [Shinyhero36/quizthing#5]
Steps to reproduce:
1. Create a question
2. Duplicate it
3. Find out that the duplicated question is labelled "Question 1"
4. Cry

Screen capture:
![image](https://github.com/Shinyhero36/quizthing/assets/67973777/22cfb1e5-da39-4185-8942-bbfabf9db83f)

**Comment by Shinyhero36** [comment]
Fixed with PR #7, thank you for reporting the issue
