### ISSUE TITLE
First question of a quiz is at an incorrect position although there are no other questions

### ISSUE THREAD

**Issue by Clembs** [Shinyhero36/quizthing#8]
Steps to reproduce:
1. Create a quiz
2. Add an question
3. Question says "Question 3/4" although there are no other questions

Screen captures:
![image](https://github.com/Shinyhero36/quizthing/assets/67973777/d2c630d3-b16f-4a29-be7d-60f56c7270fe)
![image](https://github.com/Shinyhero36/quizthing/assets/67973777/4afcbb4d-f294-41fd-8fc6-27893ad57468)

**Comment by Shinyhero36** [comment]
Fixed with *I don't know which commit/PR*
